import { GoogleGenAI } from "@google/genai";
import { GEMINI_MODEL_NAME } from "../constants";
import { BackgroundOption, ColorType } from "../types";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key not found in environment variables.");
  }
  return new GoogleGenAI({ apiKey });
};

/**
 * Swaps the background of the image using Gemini.
 * @param imageBase64 The source image in base64 format
 * @param mimeType The mime type of the image (e.g., image/jpeg)
 * @param option The selected background option
 */
export const swapBackground = async (
  imageBase64: string,
  mimeType: string,
  option: BackgroundOption
): Promise<string | null> => {
  const ai = getClient();
  
  // Clean base64 string if needed (remove header)
  const base64Data = imageBase64.split(',')[1] || imageBase64;

  let prompt = "";
  if (option.type === ColorType.TRANSPARENT) {
    // Highly specific prompt for background removal
    prompt = "Remove the background of this image completely. The output must be a PNG image with a fully transparent background (alpha channel). Precisely cut out the main subject. Do not add any background color, checkerboard pattern, or noise. Just the subject on a transparent layer.";
  } else {
    prompt = `Change the background of this image to ${option.label} (${option.value}). Ensure the background is a solid, flat color. Keep the subject lighting and details natural.`;
  }

  try {
    const response = await ai.models.generateContent({
      model: GEMINI_MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: mimeType,
              data: base64Data
            }
          },
          {
            text: prompt
          }
        ]
      }
    });

    // Extract image from response
    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData && part.inlineData.data) {
                const responseMimeType = part.inlineData.mimeType || 'image/png';
                return `data:${responseMimeType};base64,${part.inlineData.data}`;
            }
        }
    }
    
    throw new Error("No image was generated by the model.");

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to process image");
  }
};
